using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AmazonAPI
{
    public enum EReportType
    {
        Inventory,
        AllListings,
        ActiveListings,
        InactiveListings,
        OpenListings,
        OpenListingsLite,
        OpenListingsLiter,
        CanceledListings,
        SoldListings,
        ListingQualityAndSuppressedListing,
        UnshippedOrders,
        ScheduledXMLOrderReport,
        RequestedOrScheduledFlatOrder,
        FlatOrder,
        FlatOrderByLastUpdate,
        FlatOrderByOrderDate,
        XMLOrderByLastUpdate,
        XMLOrderByOrderDate,
        FlatPendingOrders,
        XMLPendingOrders,
        ConvergedFlatPendingOrders,
        FlatFeedback,
        XMLCustomerMetrics,
        FlatSettlement,
        XMLSettlement,
        FlatV2Settlement,
        FBAFulfilledShipments,
        FBAFlatAllOrdersByLastUpdate,
        FBAFlatAllOrdersByOrderDate,
        FBAXMLAllOrdersByLastUpdate,
        FBAXMLAllOrdersByOrderDate,
        FBACustomerShipmentSales,
        FBAPromotions,
        FBACustomerTaxes,
        FBAFulfilledInventory,
        FBAMultiCountryInventory,
        FBADailyInventoryHistory,
        FBAMonthlyInventoryHistory,
        FBAReceivedInventory,
        FBAReservedInventory,
        FBAInventoryEventDetail,
        FBAInventoryAdjustments,
        FBAInventoryHealth,
        FBAManageInventory,
        FBAManageInventoryArchived,
        FBACrossBorderInventoryMovement,
        RestockInventory,
        FBAInboundPerformance,
        FBAStrandedInventory,
        FBABulkFixStrandedInventory,
        FBAInventoryAge,
        FBAManageExcessInventory,
        FBAFeePreview,
        FBAReimbursments,
        FBAReturns,
        FBAReplacements,
        FBARecommendedRemoval,
        FBARemovalOrderDetail,
        FBARemovalShipmentDetail,
        SalesTax,
        BrowseTree,

    }
}
